import com.xmas.DaySix;
import org.junit.jupiter.api.Test;

public class DaySixTest {
    DaySix sut = new DaySix();

    @Test
    public void puz1Example() {
        var result = sut.puzOne(example1);
        System.out.println(result);
    }

    @Test
    public void puz1() {
        var result = sut.puzOne(input);
        System.out.println(result);
    }

    @Test
    public void puz2Example() {
        var result = sut.puzTwo(example1);
        System.out.println(result);
    }

    @Test
    public void puz2() {
        var result = sut.puzTwo(input);
        System.out.println(result);
    }

    String example1 = "abc\n" +
            "\n" +
            "a\n" +
            "b\n" +
            "c\n" +
            "\n" +
            "ab\n" +
            "ac\n" +
            "\n" +
            "a\n" +
            "a\n" +
            "a\n" +
            "a\n" +
            "\n" +
            "b";

    String input = "kimczeyaqwbs\n" +
            "pwmsf\n" +
            "wgmfus\n" +
            "lofjwnms\n" +
            "rwsum\n" +
            "\n" +
            "hndgqzkvtyxoifsemrpjaul\n" +
            "brfzpmgesjihuvxqyontdaklw\n" +
            "fakydqpuriljosvhmxtezng\n" +
            "qerstgynxplkhmoiuvzdjaf\n" +
            "\n" +
            "pxygsaovwnuqthke\n" +
            "ygqnepvuxhswtao\n" +
            "\n" +
            "o\n" +
            "o\n" +
            "\n" +
            "uogzqatjwyihskpdlen\n" +
            "wkidlyahtzougjpnseq\n" +
            "ylputjwoaizqdekgnsh\n" +
            "\n" +
            "diejltaxoqgfsckymvpwzu\n" +
            "vtypfnsojcqilbuazg\n" +
            "\n" +
            "lkvqinopx\n" +
            "gptazfonbq\n" +
            "oqahpnz\n" +
            "qpowmnb\n" +
            "neqodhjp\n" +
            "\n" +
            "hzqgiaksvouycjpwet\n" +
            "izakeohctsuypgjvwq\n" +
            "eojhzasvqitygcpwuk\n" +
            "jkstuviacphgwezyoq\n" +
            "\n" +
            "voksmqfalh\n" +
            "fywojdbrvpax\n" +
            "cefovustagzn\n" +
            "\n" +
            "wdkcuiyegrl\n" +
            "zmnixqbeyw\n" +
            "\n" +
            "sia\n" +
            "iaqpwc\n" +
            "jitvxgflyob\n" +
            "ei\n" +
            "dmic\n" +
            "\n" +
            "nixkt\n" +
            "ikcxn\n" +
            "xifkn\n" +
            "nkix\n" +
            "\n" +
            "bixymepogkvfj\n" +
            "sbunqihy\n" +
            "abcqyris\n" +
            "\n" +
            "yvhwcort\n" +
            "yhtcwrvo\n" +
            "ctwyhovr\n" +
            "wcrvhtyo\n" +
            "\n" +
            "bjvircqefhlyznsd\n" +
            "jctyeviqfrhsxzmbl\n" +
            "\n" +
            "jgrevymwlqbpunxtsfhoz\n" +
            "nbxpvrmlguijhzes\n" +
            "mjhlgexnvspuzrdb\n" +
            "pvlkjeszrahcgmxdunb\n" +
            "\n" +
            "epvajuyqngtfwdkc\n" +
            "vfpscguyjxdzqwaoin\n" +
            "lthjymuwpagvqdcnf\n" +
            "bpvkawydfcgujqn\n" +
            "\n" +
            "bitunayfdscvl\n" +
            "sfzgnmlothwcypqivd\n" +
            "ybrtcslvnkfdi\n" +
            "\n" +
            "afkcyoimgslu\n" +
            "bdnjpxzt\n" +
            "edvrqhw\n" +
            "\n" +
            "y\n" +
            "y\n" +
            "y\n" +
            "y\n" +
            "y\n" +
            "\n" +
            "bmupew\n" +
            "pxwvabek\n" +
            "\n" +
            "sbwlutnocqydxvjamz\n" +
            "hlcjwtkrxpfubdiyesvgoq\n" +
            "\n" +
            "raoskztv\n" +
            "qtepkx\n" +
            "\n" +
            "hvlygxtki\n" +
            "xltzfhim\n" +
            "tihqfxl\n" +
            "\n" +
            "fjoaqxhdwnkprb\n" +
            "szktfnhwoalvqbdicmju\n" +
            "yefnhbgaokwqdj\n" +
            "\n" +
            "ojmequvklwyazptnbfshcdi\n" +
            "nhvqyoegrwafdlmkbitsju\n" +
            "\n" +
            "bhm\n" +
            "mh\n" +
            "moh\n" +
            "hm\n" +
            "\n" +
            "lsi\n" +
            "lxsi\n" +
            "snli\n" +
            "\n" +
            "vgabusj\n" +
            "bjsuga\n" +
            "usjbag\n" +
            "ajugsb\n" +
            "\n" +
            "lgukxonpdhf\n" +
            "lqkopfxrghd\n" +
            "chxoagdlpf\n" +
            "cpdvqhgklnfobx\n" +
            "pgxzhldof\n" +
            "\n" +
            "bf\n" +
            "znb\n" +
            "\n" +
            "hpbftljasre\n" +
            "mvrecz\n" +
            "rwcienv\n" +
            "uoerxyw\n" +
            "\n" +
            "gkdmxz\n" +
            "xgkam\n" +
            "yqtxkrmjbgh\n" +
            "\n" +
            "btpsawelqygnkco\n" +
            "kwgctopbslqymane\n" +
            "wecgsoapybktnlq\n" +
            "rwlsketoagcynbpq\n" +
            "\n" +
            "wukmshcei\n" +
            "syciheuk\n" +
            "\n" +
            "sdijbqf\n" +
            "sbiaq\n" +
            "sqhtlpibn\n" +
            "\n" +
            "lvpmifrzqcyugwehn\n" +
            "wefzpvmhguiqclyrn\n" +
            "vzwfgrlpqihumenyc\n" +
            "utfmcivneqypgzlwrh\n" +
            "\n" +
            "igzcfvdokapnjuty\n" +
            "oijnzykcvpgfdut\n" +
            "oiscndvjkugptfazy\n" +
            "gmdfpobuikyhtzvncje\n" +
            "\n" +
            "bjzdqmi\n" +
            "dqmbjiz\n" +
            "qjdzkbmi\n" +
            "zdjamqib\n" +
            "idbzqjvm\n" +
            "\n" +
            "mgkodxusbcelt\n" +
            "fluxbecodmgskt\n" +
            "tuedkbyomxlscgz\n" +
            "\n" +
            "vgbjkaih\n" +
            "vsiwejlhboa\n" +
            "\n" +
            "fqhzpsnymxblvitu\n" +
            "ilavdqxyzengr\n" +
            "kyzdqgniolxcv\n" +
            "\n" +
            "zebsyhrpakdlvnwifuxt\n" +
            "dbfzlhxqjvngkormpius\n" +
            "\n" +
            "vfq\n" +
            "fnbzqs\n" +
            "fq\n" +
            "qhfck\n" +
            "dqfv\n" +
            "\n" +
            "txawg\n" +
            "zirtlkucova\n" +
            "aejtwnyd\n" +
            "\n" +
            "pjvfoihwaqxrken\n" +
            "akrfxqnojewphiv\n" +
            "bjhfvwkpesaoiqrngx\n" +
            "oipwjqxhfkvanerl\n" +
            "\n" +
            "kjv\n" +
            "kvj\n" +
            "vkj\n" +
            "vkj\n" +
            "jvk\n" +
            "\n" +
            "qglnpszvbt\n" +
            "lntbvsqzc\n" +
            "blsnqzftv\n" +
            "koztbsnqvl\n" +
            "\n" +
            "qlzcoratdnf\n" +
            "onmzcyrdqftla\n" +
            "qothflgwzcsvnuardp\n" +
            "tdaoenzfbckrqyl\n" +
            "oneflrtaqcdz\n" +
            "\n" +
            "gjparsnyhfcwoxmq\n" +
            "adinpuyfcwrhxkbemzo\n" +
            "rhwncxafgopmy\n" +
            "paytxcvhrnomwfl\n" +
            "omncwpyhxrfa\n" +
            "\n" +
            "zosxerad\n" +
            "zdsxqeoj\n" +
            "dtkxfozcse\n" +
            "hzeduxaso\n" +
            "\n" +
            "dkbvyancmhtjfuqgilsrx\n" +
            "ubjdyqhgcszafxnimvkpoltr\n" +
            "cixbehstjknafdlrgvqwm\n" +
            "\n" +
            "blptudkxqia\n" +
            "kajptmxludbeqic\n" +
            "anxidlktbpuq\n" +
            "tqaklpuxdoib\n" +
            "pbqkatlidxu\n" +
            "\n" +
            "rjupkhfimcytlowgbnze\n" +
            "wdpsagcrykxeomihtlzbf\n" +
            "\n" +
            "xkfzoluymcg\n" +
            "milckuovzfyg\n" +
            "omcfkyuzlg\n" +
            "fogzcklmyu\n" +
            "gqoyckuflamz\n" +
            "\n" +
            "xuywv\n" +
            "ewuy\n" +
            "byuwpgt\n" +
            "wuvyjx\n" +
            "\n" +
            "rtfbcjkhzxvwdeqmyl\n" +
            "whqtmkloecxrzdiynb\n" +
            "\n" +
            "tlakqwy\n" +
            "lwtaqy\n" +
            "ayqwtl\n" +
            "wlctaqoy\n" +
            "yqlwat\n" +
            "\n" +
            "qme\n" +
            "qme\n" +
            "eqm\n" +
            "mqe\n" +
            "\n" +
            "nwmrsflpcay\n" +
            "tafprnwlcmy\n" +
            "wacgprmnylf\n" +
            "\n" +
            "jghyvk\n" +
            "wmspcyr\n" +
            "yxalebn\n" +
            "hvy\n" +
            "\n" +
            "okqbazsh\n" +
            "ztlbkahpxow\n" +
            "kuozahb\n" +
            "oazkhb\n" +
            "\n" +
            "ovnaqcg\n" +
            "jarbe\n" +
            "\n" +
            "xdjuzohfnvqyrag\n" +
            "exbqnyovrifuzjawhdsp\n" +
            "jhvfyrdnouaxqz\n" +
            "favdqhyuljxogrzn\n" +
            "rfnxduaqvzhjoy\n" +
            "\n" +
            "clx\n" +
            "nx\n" +
            "\n" +
            "hxr\n" +
            "urhx\n" +
            "lxrh\n" +
            "nhrx\n" +
            "\n" +
            "czafkt\n" +
            "tkoc\n" +
            "tck\n" +
            "\n" +
            "wjyxhcemqopsif\n" +
            "yeosjmfxqhcpiw\n" +
            "jfmewqsyhpocxi\n" +
            "ehcoxyjiqmpsfw\n" +
            "jhmevpoxqsagfwyciz\n" +
            "\n" +
            "vzwsc\n" +
            "cswzv\n" +
            "\n" +
            "yihqcvgmswr\n" +
            "lhyonpzbvcegwaxs\n" +
            "iuwhcsykgv\n" +
            "vitfywgcqushd\n" +
            "\n" +
            "sprazqldenowck\n" +
            "cnwqlsead\n" +
            "\n" +
            "vycjno\n" +
            "jndiofc\n" +
            "enycjo\n" +
            "cejon\n" +
            "\n" +
            "cz\n" +
            "zjc\n" +
            "zc\n" +
            "kzc\n" +
            "\n" +
            "uqz\n" +
            "qaz\n" +
            "qz\n" +
            "zq\n" +
            "nqyxbzlg\n" +
            "\n" +
            "msgvcra\n" +
            "clugnjfrqwdky\n" +
            "\n" +
            "tuambvhyxkjgworeqlcd\n" +
            "gqtcjynbkhrowdpfmlz\n" +
            "\n" +
            "njfud\n" +
            "fdiunj\n" +
            "nudjf\n" +
            "ujdnf\n" +
            "\n" +
            "vxcdygpf\n" +
            "c\n" +
            "sajc\n" +
            "\n" +
            "ednfp\n" +
            "nzmoeptdf\n" +
            "envqdfp\n" +
            "nqdpvejf\n" +
            "\n" +
            "zbljntm\n" +
            "mnyzbrepj\n" +
            "jnmzbqwcd\n" +
            "bzmjun\n" +
            "\n" +
            "freopjitc\n" +
            "ubesxqzytpaj\n" +
            "\n" +
            "chu\n" +
            "cyhu\n" +
            "uohc\n" +
            "\n" +
            "kucjmgxbz\n" +
            "sfgwdht\n" +
            "\n" +
            "vhsft\n" +
            "sfvt\n" +
            "tsvf\n" +
            "\n" +
            "fmkcjeahvo\n" +
            "omafzjchvk\n" +
            "jcmhafslekov\n" +
            "mhfvjxcako\n" +
            "yfkjwovhacm\n" +
            "\n" +
            "omqwalvbhnctzksd\n" +
            "dmhcwgokvzatsjypqxn\n" +
            "\n" +
            "rae\n" +
            "rae\n" +
            "\n" +
            "krsfvuilhp\n" +
            "afwbrmo\n" +
            "\n" +
            "gforteuvwbdhlynapm\n" +
            "pdnwtomyefluhrba\n" +
            "skmtwbadfouxnyerl\n" +
            "tblojwfermudany\n" +
            "orbumjtleawdnyf\n" +
            "\n" +
            "pkzbnaieqxdhwcv\n" +
            "ufvzmcoqxkiwadsgh\n" +
            "\n" +
            "pfjqir\n" +
            "qprjif\n" +
            "pfjdrx\n" +
            "pfrncteaj\n" +
            "\n" +
            "zctvj\n" +
            "cvjz\n" +
            "ujgclzv\n" +
            "cjhvz\n" +
            "\n" +
            "qsdhlyojwckxt\n" +
            "jycqdto\n" +
            "\n" +
            "lyin\n" +
            "inyl\n" +
            "ynli\n" +
            "\n" +
            "mepna\n" +
            "mpuqna\n" +
            "mplan\n" +
            "qnmljap\n" +
            "gmpcknvhaw\n" +
            "\n" +
            "dwlgfkbytpsvzrhocmx\n" +
            "yzqvxkdtrscopgfwlm\n" +
            "vprkldmyqeogfwtczxs\n" +
            "cqlmtbxzwvprgsfkody\n" +
            "utmpyvgasxkdofwrclzi\n" +
            "\n" +
            "arsgpnjowxikdmuzy\n" +
            "aqsgwijynldzcuk\n" +
            "\n" +
            "yahsrdx\n" +
            "raxyhsd\n" +
            "hxadyrs\n" +
            "\n" +
            "wracz\n" +
            "car\n" +
            "rcaw\n" +
            "akqrc\n" +
            "\n" +
            "ztecarjfvpyu\n" +
            "fzpemyuaxctjr\n" +
            "\n" +
            "ubzyxt\n" +
            "ixtqnpkrdcsway\n" +
            "\n" +
            "jvczubednmhflwg\n" +
            "zgcjlhduevwnfmb\n" +
            "\n" +
            "nmrghqdwcpb\n" +
            "drnhcwgpbmq\n" +
            "gwmcdqphbrn\n" +
            "gbrqwnphdcm\n" +
            "bgdhmrpnwcq\n" +
            "\n" +
            "aulwoc\n" +
            "aoluc\n" +
            "laouc\n" +
            "luaoc\n" +
            "\n" +
            "mieafvsbwzcj\n" +
            "scwmfvjabzie\n" +
            "zfvcawsbximeju\n" +
            "wbizefvhjmcas\n" +
            "cwsihjbvmzafe\n" +
            "\n" +
            "e\n" +
            "e\n" +
            "se\n" +
            "\n" +
            "qhjlkwfux\n" +
            "xqhflujwk\n" +
            "kwxuljqhf\n" +
            "whkuxlqjf\n" +
            "fkluqjwhx\n" +
            "\n" +
            "ukbghtdnmrof\n" +
            "svlkyaiqwtzxnbegfroj\n" +
            "grbcpnotkf\n" +
            "\n" +
            "ebtdjpzak\n" +
            "tdpyjzanhe\n" +
            "ajzudbitple\n" +
            "eapvjtmgfqdczx\n" +
            "paesdtjz\n" +
            "\n" +
            "hyunpcexs\n" +
            "crzuebywkx\n" +
            "hfcueygx\n" +
            "sequxcy\n" +
            "cxmyeigqu\n" +
            "\n" +
            "xhojpeuifkwagclnmbsyv\n" +
            "ntzedpgqrlb\n" +
            "\n" +
            "tjcfwyhn\n" +
            "tjysuw\n" +
            "jxgywtp\n" +
            "wvjezyta\n" +
            "ypjwdbsti\n" +
            "\n" +
            "kgujzftcnrh\n" +
            "krjmungthcz\n" +
            "ztuprhcnjgemv\n" +
            "thbdcrugnzjx\n" +
            "fsruzjyhlngcte\n" +
            "\n" +
            "ubwhla\n" +
            "buwl\n" +
            "lbhu\n" +
            "wabul\n" +
            "bilnkufp\n" +
            "\n" +
            "lpymwtbquzk\n" +
            "bmdptuyqwvlzk\n" +
            "qupkwmtzybl\n" +
            "zypmlkqubwt\n" +
            "wzlytqupbmk\n" +
            "\n" +
            "fkshlxgywjaz\n" +
            "bfljvakghypxscw\n" +
            "ndkolixfjtasyumqwhg\n" +
            "\n" +
            "ygokenlwrubf\n" +
            "nflkubozyj\n" +
            "ofklynquzb\n" +
            "ybkflpuon\n" +
            "\n" +
            "rh\n" +
            "hr\n" +
            "rh\n" +
            "lhr\n" +
            "\n" +
            "qygxmfrzwodv\n" +
            "zrdqgyoxmwvf\n" +
            "rofdxwyvgmqz\n" +
            "grvfydzxqomw\n" +
            "fwqrgmzvdoyx\n" +
            "\n" +
            "domictwezlursy\n" +
            "jrsmzongcax\n" +
            "cxzsporm\n" +
            "jmgzofnqvscr\n" +
            "\n" +
            "ot\n" +
            "ojt\n" +
            "to\n" +
            "ot\n" +
            "to\n" +
            "\n" +
            "tsziwcmhlpgebfxdanujqov\n" +
            "dtnmjisavlbporqwyzefukh\n" +
            "\n" +
            "aigqlkjyprvcztxfdhmwunb\n" +
            "zcaypfrthmikvuqwlnbdjgx\n" +
            "jbczgwnqdyvuamkixrpfhlt\n" +
            "qiuhwvplyntgrfmdbckzxja\n" +
            "\n" +
            "ekjsdwp\n" +
            "dpueswk\n" +
            "\n" +
            "bxmqup\n" +
            "gujpqnxm\n" +
            "qpvomxu\n" +
            "mhqwclaypxz\n" +
            "xiqmspd\n" +
            "\n" +
            "u\n" +
            "nds\n" +
            "mu\n" +
            "u\n" +
            "\n" +
            "ucz\n" +
            "u\n" +
            "u\n" +
            "ku\n" +
            "\n" +
            "whvxtgpfc\n" +
            "xhqrlbtc\n" +
            "uakhdcyz\n" +
            "\n" +
            "fr\n" +
            "mc\n" +
            "\n" +
            "dugf\n" +
            "dfug\n" +
            "dfgju\n" +
            "\n" +
            "blgkyqwsmeunr\n" +
            "lenpmqgstbrhyu\n" +
            "\n" +
            "gyadp\n" +
            "adyp\n" +
            "oywdapc\n" +
            "\n" +
            "ulmqnatkcz\n" +
            "manlczukqt\n" +
            "mqzlnkucat\n" +
            "\n" +
            "ibfldxqgvhyntomew\n" +
            "oydfwnhtqblivemgx\n" +
            "wlbfgquthnydmixvoe\n" +
            "\n" +
            "ghfurqksbxdevawmnzoijlp\n" +
            "aolfhvksrgxziwbedmjqupn\n" +
            "jqzdrhsbxmknolwvaipfgeu\n" +
            "\n" +
            "owpunqvembjgh\n" +
            "mrutexapbksd\n" +
            "\n" +
            "vwzrstglah\n" +
            "shltgbzw\n" +
            "wltgbszh\n" +
            "ghztwls\n" +
            "tgshzlw\n" +
            "\n" +
            "umhfe\n" +
            "fm\n" +
            "mf\n" +
            "mf\n" +
            "mf\n" +
            "\n" +
            "rjbleoux\n" +
            "juelcxb\n" +
            "wexihyfvtmbsk\n" +
            "\n" +
            "eqoxpwrdvjksmtgfacly\n" +
            "mjcladsvxwtqroyekpgf\n" +
            "evmkxltqwosdycfparjg\n" +
            "tewfspajodcvxgkyrlqm\n" +
            "\n" +
            "nekh\n" +
            "knhe\n" +
            "ehkn\n" +
            "\n" +
            "lechzpmjqsiayk\n" +
            "kavhyumj\n" +
            "\n" +
            "ylqawcxvjfdbrit\n" +
            "qidrcwtalfhn\n" +
            "zatfcqpwrydilx\n" +
            "relmsdqafgtciuw\n" +
            "ihdfalwctxrkq\n" +
            "\n" +
            "wnlpkdogmtjry\n" +
            "hysrgpnodcmwktl\n" +
            "myldprketognw\n" +
            "kdwptoylmbrng\n" +
            "lwgrutpykndmo\n" +
            "\n" +
            "krhviqalxtzpbmjodcwy\n" +
            "lakvhqwijroxmpbtdz\n" +
            "uolpxarzsqtwgbhvjmdki\n" +
            "pzkbavixjdtrmgholwq\n" +
            "\n" +
            "smdjla\n" +
            "asdmlj\n" +
            "sjalm\n" +
            "safmjl\n" +
            "\n" +
            "suxodwmkpya\n" +
            "ctouegzhqpbws\n" +
            "rjlnviw\n" +
            "\n" +
            "tjzcenpgwhry\n" +
            "wjehcygpzrtn\n" +
            "eywcgtjprznh\n" +
            "tgzypcwrnjhe\n" +
            "\n" +
            "mkrbaxvth\n" +
            "vhkbmxr\n" +
            "\n" +
            "yejbkoatwshxgrf\n" +
            "rbltwyeshjfkaonxg\n" +
            "\n" +
            "qpynbcmgwei\n" +
            "bwngqymhis\n" +
            "gxrilonymqwb\n" +
            "mwybqzintg\n" +
            "pmjwsngdiqykb\n" +
            "\n" +
            "ipauz\n" +
            "azpuis\n" +
            "\n" +
            "bslptiuy\n" +
            "flbgprtsyi\n" +
            "nyqtlbjips\n" +
            "siguypltbf\n" +
            "sbktylpi\n" +
            "\n" +
            "dchsxpevkamwb\n" +
            "vaxebskdhfc\n" +
            "vclhkgmxadoesb\n" +
            "xbqsuhvdryikczae\n" +
            "\n" +
            "gsq\n" +
            "gsq\n" +
            "qsg\n" +
            "qsg\n" +
            "qgs\n" +
            "\n" +
            "tfv\n" +
            "ws\n" +
            "\n" +
            "h\n" +
            "h\n" +
            "h\n" +
            "\n" +
            "yqant\n" +
            "kcxjsl\n" +
            "\n" +
            "murkbfphvcdxjoltanyq\n" +
            "bgphukfmnadixyrqvjlotc\n" +
            "lukptvynjizhfrxmqodacb\n" +
            "htvxocyfnkrplubadmqj\n" +
            "juoadmclhytrfpxwvnkbq\n" +
            "\n" +
            "evoxmajwzhri\n" +
            "ovzhiaemrxwj\n" +
            "rzjwhxmieovab\n" +
            "jmrzwoaheivcx\n" +
            "mexrqihvawnozj\n" +
            "\n" +
            "hjkqrtolspfwzeymbvxci\n" +
            "dswthxvfjizypockrqlbe\n" +
            "\n" +
            "hwjbnaqyfxmtp\n" +
            "xhynbafjwmqtp\n" +
            "pxthujyambfwnq\n" +
            "nahwjtmfxqbpy\n" +
            "abhqfwmxjpytn\n" +
            "\n" +
            "sxlcikh\n" +
            "jhxi\n" +
            "ixk\n" +
            "iuxtrov\n" +
            "\n" +
            "pahzgxyfsovw\n" +
            "vfgyxaulphosw\n" +
            "kyohxvawsgpf\n" +
            "\n" +
            "ktyldbgmnezupwhifjqa\n" +
            "moavjubleydwpnhkft\n" +
            "nfyaewbljdmpoukht\n" +
            "\n" +
            "qlnkitdzpw\n" +
            "shkquxnfwcbldiz\n" +
            "\n" +
            "xcydfaphz\n" +
            "phuzctyxdeg\n" +
            "xzmyhpdc\n" +
            "zhpcdxy\n" +
            "yahszdcxp\n" +
            "\n" +
            "pziwnkcrlaegvqm\n" +
            "vketnqmogifpx\n" +
            "\n" +
            "pgkywbz\n" +
            "yicb\n" +
            "ybl\n" +
            "by\n" +
            "bsyc\n" +
            "\n" +
            "w\n" +
            "w\n" +
            "wf\n" +
            "nw\n" +
            "yxpw\n" +
            "\n" +
            "xkowlzyfg\n" +
            "kzxelo\n" +
            "zljoxk\n" +
            "zxklo\n" +
            "\n" +
            "on\n" +
            "zbmof\n" +
            "zwe\n" +
            "m\n" +
            "qjst\n" +
            "\n" +
            "bvxurajphwotlfg\n" +
            "plbtxughrafwvjo\n" +
            "tvxagjfwuroplhkb\n" +
            "fvswogtjarhbplxu\n" +
            "gztjypobcxnfwaqehvlru\n" +
            "\n" +
            "rlmuqjvbsyhd\n" +
            "mvldbqrkjusp\n" +
            "\n" +
            "kogjn\n" +
            "kjgon\n" +
            "kongj\n" +
            "jkngo\n" +
            "gznjok\n" +
            "\n" +
            "jwryklzmitdop\n" +
            "tysrjdw\n" +
            "bjydrntwu\n" +
            "aytwdrj\n" +
            "dywvjtr\n" +
            "\n" +
            "hocrsimfaeuxnld\n" +
            "kdxbfilqwch\n" +
            "\n" +
            "haldjczwifbkymosgrpxq\n" +
            "cwmdjlrbfyxkphisgoa\n" +
            "lsfcimdbphyoajgwkrx\n" +
            "mgdpotylkfxwsachbrij\n" +
            "imyplbjdshxwrfocgka\n" +
            "\n" +
            "rdywe\n" +
            "eyzbw\n" +
            "ey\n" +
            "oreqy\n" +
            "yiue\n" +
            "\n" +
            "juxv\n" +
            "uxjv\n" +
            "jvkx\n" +
            "vxj\n" +
            "\n" +
            "p\n" +
            "pk\n" +
            "p\n" +
            "p\n" +
            "\n" +
            "evyxnjfhbukctls\n" +
            "knsxtcfbuehyv\n" +
            "yenkbfustcvxh\n" +
            "fhbcnuseyvktx\n" +
            "\n" +
            "jrbpsediyuxkz\n" +
            "ivqtewhyomzc\n" +
            "\n" +
            "phfebgdqylnitv\n" +
            "livhqmtypbedgf\n" +
            "hvbiyfgpteldq\n" +
            "vhtgbpeyifqdl\n" +
            "tglbdchfaoypieqv\n" +
            "\n" +
            "siyn\n" +
            "isyhn\n" +
            "\n" +
            "tzhdfkl\n" +
            "njypvuwamecgsq\n" +
            "ilbxht\n" +
            "ro\n" +
            "x\n" +
            "\n" +
            "fcdqjmwop\n" +
            "omqfwjcpk\n" +
            "\n" +
            "luiexa\n" +
            "alxuie\n" +
            "iauexl\n" +
            "\n" +
            "wab\n" +
            "aw\n" +
            "wa\n" +
            "aw\n" +
            "aw\n" +
            "\n" +
            "njghb\n" +
            "gjbhn\n" +
            "bnhs\n" +
            "bnh\n" +
            "dbnhp\n" +
            "\n" +
            "qflcvbpwger\n" +
            "lhycovbxqrwe\n" +
            "\n" +
            "pnrulmeoy\n" +
            "ernsopmylu\n" +
            "\n" +
            "rawysqzlfjd\n" +
            "ryzlfqdaswj\n" +
            "rjfsdqalyzw\n" +
            "fjardzqswyl\n" +
            "wljfrqzadys\n" +
            "\n" +
            "cl\n" +
            "cl\n" +
            "lc\n" +
            "lc\n" +
            "cl\n" +
            "\n" +
            "qxpjwuktzdvcengfmalhr\n" +
            "hrjmudvwzckogtpfexq\n" +
            "jqzckrthdwxupgevmf\n" +
            "zxuehptkqcjgdmrwvbfi\n" +
            "\n" +
            "d\n" +
            "d\n" +
            "\n" +
            "lr\n" +
            "lr\n" +
            "alhpr\n" +
            "rl\n" +
            "\n" +
            "mfjlbitn\n" +
            "mnfijgblst\n" +
            "lftnmibj\n" +
            "\n" +
            "rjsvglpamuqtkf\n" +
            "gjfqaxtskcvrlupm\n" +
            "pqgatujsmvflrk\n" +
            "vagkpusfljmqrwt\n" +
            "\n" +
            "o\n" +
            "o\n" +
            "\n" +
            "bfdw\n" +
            "btgw\n" +
            "mbqw\n" +
            "\n" +
            "pztgnlfjrosdy\n" +
            "jusgnqobytlhr\n" +
            "ltfpnsagoryjd\n" +
            "jogwrilnstym\n" +
            "\n" +
            "kba\n" +
            "ak\n" +
            "mrsocfjn\n" +
            "qd\n" +
            "a\n" +
            "\n" +
            "hiwjx\n" +
            "ishdwjx\n" +
            "wxihjey\n" +
            "xhwij\n" +
            "\n" +
            "p\n" +
            "pg\n" +
            "p\n" +
            "p\n" +
            "p\n" +
            "\n" +
            "qgptrvo\n" +
            "fgprtvq\n" +
            "\n" +
            "cqdzir\n" +
            "zrsc\n" +
            "kzxbcjr\n" +
            "lcxkzrwq\n" +
            "\n" +
            "zjanetblwcisodmkghrfvxyp\n" +
            "egszxvpcmrlitwjnbhofayk\n" +
            "zwnxmrjiypctkfeblhavsgo\n" +
            "retfmziplhgkwxanosjcybv\n" +
            "\n" +
            "gsodevhlix\n" +
            "jizguohlv\n" +
            "xvsgohilck\n" +
            "mvlyisogh\n" +
            "kovebflihg\n" +
            "\n" +
            "qagwb\n" +
            "awbq\n" +
            "aqwbt\n" +
            "\n" +
            "pckgorutxfn\n" +
            "pusrhocxnk\n" +
            "nokrclxmup\n" +
            "orpmcunlkx\n" +
            "\n" +
            "ybsrzvtophijcx\n" +
            "xohyprbzijtvs\n" +
            "yxirztpvhbosqj\n" +
            "htgzopxkjeribsyfvm\n" +
            "vjzthsoprybqxi\n" +
            "\n" +
            "xdgjiapumqth\n" +
            "doyirnhfgbxcpa\n" +
            "gqdpkhavxiwj\n" +
            "\n" +
            "gmeyf\n" +
            "fmgey\n" +
            "mgyef\n" +
            "meygf\n" +
            "fgmeyr\n" +
            "\n" +
            "jtsvqnf\n" +
            "nfjet\n" +
            "ndktfj\n" +
            "\n" +
            "zhfblxrng\n" +
            "lnbzprgf\n" +
            "fisqavznlbmcgdt\n" +
            "nflgzb\n" +
            "\n" +
            "exgjnzsarhvpmwd\n" +
            "uozjhrwvdxeabngmps\n" +
            "vwsxgeadhjpmynrz\n" +
            "mdexrhazsgjnpwv\n" +
            "hzaerjxvgdwnkpsm\n" +
            "\n" +
            "ybo\n" +
            "oby\n" +
            "boy\n" +
            "boy\n" +
            "\n" +
            "skzat\n" +
            "tzks\n" +
            "\n" +
            "jai\n" +
            "aij\n" +
            "yerigcdtx\n" +
            "piqoz\n" +
            "\n" +
            "k\n" +
            "km\n" +
            "lk\n" +
            "ky\n" +
            "\n" +
            "szcvjaehuwbqg\n" +
            "jbavewzcuhsgq\n" +
            "sepbuzvqwjhgac\n" +
            "zbvwajqcueshg\n" +
            "vhwgbjeqzscua\n" +
            "\n" +
            "mn\n" +
            "mnk\n" +
            "gnlm\n" +
            "nm\n" +
            "pnm\n" +
            "\n" +
            "vknrswebxhqip\n" +
            "rhbxqskwpei\n" +
            "sbwhqreikpx\n" +
            "pxkigfwrbehsmq\n" +
            "qiezrhkxspwb\n" +
            "\n" +
            "pgsfdiuyv\n" +
            "yfqdivgsu\n" +
            "yuigvdsf\n" +
            "\n" +
            "mlnxbavsrfkoh\n" +
            "ifrlvdsoan\n" +
            "\n" +
            "hypxobcrwj\n" +
            "pbyhjcwxro\n" +
            "\n" +
            "edcktsrh\n" +
            "hcvrs\n" +
            "rshiqmx\n" +
            "rphltsb\n" +
            "tsrlhu\n" +
            "\n" +
            "swdx\n" +
            "xpqw\n" +
            "oxrgwkq\n" +
            "xpfw\n" +
            "lcmtuwxyz\n" +
            "\n" +
            "zjfqilswdtrnecm\n" +
            "lqsyndmjfrzwcie\n" +
            "drzflgswijnqxec\n" +
            "qmlnpzkdisfrtcejw\n" +
            "\n" +
            "rhvsfaopuc\n" +
            "ouiafvwsp\n" +
            "sadwfopukgvn\n" +
            "\n" +
            "bca\n" +
            "hlaicm\n" +
            "acreb\n" +
            "awcb\n" +
            "cga\n" +
            "\n" +
            "bkprumswqvjexofy\n" +
            "bredoqvxmwulfjyktc\n" +
            "sqyobfurpwvjxemk\n" +
            "qbuwsemkrjgvfoiyx\n" +
            "\n" +
            "blecimw\n" +
            "ibevxwozml\n" +
            "lbwimce\n" +
            "\n" +
            "zvmaiotju\n" +
            "gubo\n" +
            "bgowu\n" +
            "\n" +
            "uvycgfrzsa\n" +
            "svqczgeafyrbn\n" +
            "\n" +
            "wikumtyzq\n" +
            "oyidem\n" +
            "\n" +
            "acupgo\n" +
            "pou\n" +
            "opu\n" +
            "\n" +
            "semhzkwbpf\n" +
            "swmphbzfke\n" +
            "zwkmsbpefh\n" +
            "hsfpmekzwb\n" +
            "kewmzpsfhb\n" +
            "\n" +
            "bn\n" +
            "n\n" +
            "n\n" +
            "n\n" +
            "\n" +
            "qbu\n" +
            "ubq\n" +
            "\n" +
            "vylgakednfuji\n" +
            "bneplxayidkcvgu\n" +
            "hedqwrzmyulstokva\n" +
            "\n" +
            "xfczwpihktmovlygjqu\n" +
            "vbujlkoxwftmnaizhpgcq\n" +
            "zgkixlomvnuqwtjpscfh\n" +
            "\n" +
            "wld\n" +
            "pl\n" +
            "lp\n" +
            "lq\n" +
            "\n" +
            "qspzfkvcj\n" +
            "jkvsgqcfp\n" +
            "ptdcswkavqyjfo\n" +
            "\n" +
            "rkv\n" +
            "nryvux\n" +
            "vrgob\n" +
            "ynkarmv\n" +
            "\n" +
            "ypfolxac\n" +
            "awmnxviqfto\n" +
            "ofxsba\n" +
            "fahtbosx\n" +
            "safwnorbx\n" +
            "\n" +
            "hyxdzilaqcufktnjs\n" +
            "mzuojklqatchfxnyid\n" +
            "tuqysahkcnfdzlbijx\n" +
            "ctjxdkfzynalqhiu\n" +
            "\n" +
            "iekbthlywpqog\n" +
            "riqcesvgz\n" +
            "liqpkedofgt\n" +
            "\n" +
            "kgowrmzt\n" +
            "owhizkmd\n" +
            "wfkzoixsm\n" +
            "oyjkwzvlmqpb\n" +
            "\n" +
            "rh\n" +
            "hr\n" +
            "rhlt\n" +
            "hr\n" +
            "hr\n" +
            "\n" +
            "flwgecipkhrov\n" +
            "retphkfvlocgiw\n" +
            "wckgliefhrpov\n" +
            "wigkprhlcvfoe\n" +
            "opwilkegfrvhc\n" +
            "\n" +
            "xvycoqmr\n" +
            "mixnvqkroy\n" +
            "cmvroyqx\n" +
            "cqomrxvy\n" +
            "\n" +
            "leaxtowgyfusvn\n" +
            "vkftjhi\n" +
            "mvtpjf\n" +
            "hbpqcztfvr\n" +
            "\n" +
            "gjntfylqv\n" +
            "jfngqlv\n" +
            "lvgjqfn\n" +
            "fvqjlgn\n" +
            "\n" +
            "f\n" +
            "a\n" +
            "\n" +
            "bz\n" +
            "ybz\n" +
            "zb\n" +
            "bz\n" +
            "zb\n" +
            "\n" +
            "vydulosmfjci\n" +
            "ahbzxndwtmruvfqgpkj\n" +
            "\n" +
            "qskd\n" +
            "p\n" +
            "h\n" +
            "h\n" +
            "\n" +
            "ynxcwptkvjrlzbuqdeom\n" +
            "iocjykshxunqtr\n" +
            "ctynkrjxuhoq\n" +
            "\n" +
            "lxhdvw\n" +
            "mgneql\n" +
            "lh\n" +
            "xvdrl\n" +
            "\n" +
            "ipn\n" +
            "pmin\n" +
            "\n" +
            "fjslnqizrwdugvtp\n" +
            "gflntqsdvirwjpzu\n" +
            "szfigtrqnudvlpjw\n" +
            "vznlswjgqcitfudpxr\n" +
            "pfiwsgznluqrjtdv\n" +
            "\n" +
            "fwydsbojgqnkc\n" +
            "oqyjndwfbkcgs\n" +
            "qdbwjgkcfsyno\n" +
            "fnjyqkdscobwg\n" +
            "fyjbdkgwoqcsn\n" +
            "\n" +
            "tepdyr\n" +
            "rdpe\n" +
            "sdxplfwer\n" +
            "ydrep\n" +
            "rpyzed\n" +
            "\n" +
            "y\n" +
            "r\n" +
            "r\n" +
            "\n" +
            "ojck\n" +
            "kjco\n" +
            "ojmkc\n" +
            "ckoj\n" +
            "\n" +
            "ursaovzdi\n" +
            "lxsbfyegq\n" +
            "\n" +
            "zb\n" +
            "bz\n" +
            "\n" +
            "wzyna\n" +
            "zi\n" +
            "hzbuv\n" +
            "\n" +
            "vcjzkqs\n" +
            "jtzksvq\n" +
            "vqjzslhk\n" +
            "\n" +
            "nabjpwyq\n" +
            "\n" +
            "d\n" +
            "ls\n" +
            "xd\n" +
            "y\n" +
            "v\n" +
            "\n" +
            "bog\n" +
            "dk\n" +
            "\n" +
            "wdhflrxqisynumgvckpzaob\n" +
            "ormgkwnqbzvhlsyxduiacpf\n" +
            "gptouzfbrdaeinqcslmywxvkh\n" +
            "\n" +
            "gjqpaownevz\n" +
            "zwnjqp\n" +
            "jzqwlpn\n" +
            "ljwpqzdn\n" +
            "\n" +
            "wfrmqiavepl\n" +
            "vilqafmwrhsep\n" +
            "alqvrwpfmie\n" +
            "qpelarmwvfi\n" +
            "\n" +
            "z\n" +
            "z\n" +
            "z\n" +
            "z\n" +
            "z\n" +
            "\n" +
            "cbra\n" +
            "absrc\n" +
            "arcb\n" +
            "\n" +
            "fyotgixvpuhmejnwr\n" +
            "kjpqazlygts\n" +
            "\n" +
            "bcwamxoyvu\n" +
            "cbvxynowum\n" +
            "ybvwmucxkpoj\n" +
            "cuxwvybmo\n" +
            "\n" +
            "zbjealfshyut\n" +
            "prxqnilaz\n" +
            "klwgozax\n" +
            "aczln\n" +
            "\n" +
            "nfbwtpa\n" +
            "mpudjgskelqbhzfv\n" +
            "\n" +
            "wcfbvhd\n" +
            "fhdvcwb\n" +
            "chfvdwb\n" +
            "wcfhrbmvd\n" +
            "\n" +
            "advfcbwh\n" +
            "rwucbvda\n" +
            "\n" +
            "wezpclrtvgxnb\n" +
            "xwrzfpnvgbl\n" +
            "rbvgzqxnpl\n" +
            "luoakpsxmdrgbzvy\n" +
            "\n" +
            "jynkfstombapvqhdex\n" +
            "tlkhjsibqynvwmeaux\n" +
            "\n" +
            "zceihofwba\n" +
            "bopifeczwh\n" +
            "deixomckwfz\n" +
            "\n" +
            "taykiuesxbndzqholgvm\n" +
            "ekzxslvmyothgnaudq\n" +
            "atumxdzyqlhvgesnok\n" +
            "oxsmqudvgehtylkanz\n" +
            "\n" +
            "vwfdcjhgbqytlzro\n" +
            "fdrzjlcyqobvw\n" +
            "fwvrozlejbdcnyq\n" +
            "bafldoczwryjuqvn\n" +
            "\n" +
            "vhuk\n" +
            "hkvur\n" +
            "vmhku\n" +
            "bhkvu\n" +
            "hkvmu\n" +
            "\n" +
            "raiszytwogqj\n" +
            "rwajsqkiyzto\n" +
            "izgjwyosatrq\n" +
            "rayszwqoitj\n" +
            "sojyiwtzqrga\n" +
            "\n" +
            "vjuyizhqrtfcwxa\n" +
            "cifosaqwyzvgrphjx\n" +
            "vhyxtrfajqzwic\n" +
            "miqxhrfcbjawyvuz\n" +
            "\n" +
            "gsrqlwfd\n" +
            "lydsgwipqf\n" +
            "\n" +
            "gqafbew\n" +
            "fabqgewk\n" +
            "wgqfbae\n" +
            "abqehwgf\n" +
            "\n" +
            "uaxc\n" +
            "cajx\n" +
            "axlcr\n" +
            "rcxap\n" +
            "acxlp\n" +
            "\n" +
            "ehkoaumb\n" +
            "kmfnpsdwlxicgtr\n" +
            "vqmjky\n" +
            "vemk\n" +
            "\n" +
            "sj\n" +
            "s\n" +
            "si\n" +
            "\n" +
            "akosi\n" +
            "siko\n" +
            "siokn\n" +
            "oski\n" +
            "kois\n" +
            "\n" +
            "fdvq\n" +
            "msrhou\n" +
            "\n" +
            "hregctbqxlndk\n" +
            "bdqgletxhrwk\n" +
            "\n" +
            "ktx\n" +
            "tk\n" +
            "\n" +
            "roj\n" +
            "okr\n" +
            "xorv\n" +
            "\n" +
            "usofjlmex\n" +
            "lfjmndrs\n" +
            "svcmwljfgbyipa\n" +
            "lsmjnf\n" +
            "\n" +
            "rx\n" +
            "x\n" +
            "x\n" +
            "x\n" +
            "\n" +
            "twzi\n" +
            "cwotz\n" +
            "wzkt\n" +
            "\n" +
            "uewctzgvkoj\n" +
            "cutzkwjoelv\n" +
            "\n" +
            "yjkigdqnmbevtpz\n" +
            "bycktedpmzjxqin\n" +
            "prwzmokeiqtnjbyda\n" +
            "kpundeybtjmqzi\n" +
            "nzjikqedmphybt\n" +
            "\n" +
            "gbx\n" +
            "hgyj\n" +
            "bgf\n" +
            "sgtur\n" +
            "bcgkm\n" +
            "\n" +
            "e\n" +
            "d\n" +
            "e\n" +
            "\n" +
            "ilsugkx\n" +
            "slkigxu\n" +
            "iuslkxg\n" +
            "\n" +
            "dlpvungoktesibcf\n" +
            "gtopsufinlcvkbed\n" +
            "\n" +
            "fr\n" +
            "rf\n" +
            "rf\n" +
            "fr\n" +
            "fr\n" +
            "\n" +
            "mqwfpvkxds\n" +
            "vmadqpxsfwk\n" +
            "nfmjwxrqdkvsp\n" +
            "qvdfwsmxkp\n" +
            "\n" +
            "ihypftmwkjavezgbxc\n" +
            "qgvtnsahxyjflzwrcudkm\n" +
            "\n" +
            "fvxgnkim\n" +
            "ivxknbz\n" +
            "vyaqtxunjhwdiock\n" +
            "nikgpsvxl\n" +
            "bexfznikv\n" +
            "\n" +
            "ue\n" +
            "eu\n" +
            "ue\n" +
            "ue\n" +
            "ue\n" +
            "\n" +
            "tuvesnfjalybpk\n" +
            "qkvdehcpyabfjts\n" +
            "pvebjtasfky\n" +
            "vahptfeckysbj\n" +
            "\n" +
            "aynlzfvwbeg\n" +
            "eawybzgfnl\n" +
            "\n" +
            "meydqlkijc\n" +
            "qcyidlmjek\n" +
            "cmyjeklqd\n" +
            "yjclqmeksfd\n" +
            "\n" +
            "mrbucoztgpqwhjikvnxdsafl\n" +
            "dmcgjwboqxlaizptnvfhkrs\n" +
            "molqvxhabswgfnzirkpjtdc\n" +
            "\n" +
            "rn\n" +
            "gn\n" +
            "ng\n" +
            "gn\n" +
            "\n" +
            "fjrkxcm\n" +
            "mflwtcjx\n" +
            "ynuxsmpezvjc\n" +
            "dtcxbmj\n" +
            "\n" +
            "qtrehmbgscl\n" +
            "huqdcftsbeoyvrlk\n" +
            "rnlehgqzbwctpjs\n" +
            "\n" +
            "wlsrzymhpu\n" +
            "gwcmrhzlpjyu\n" +
            "\n" +
            "auqycw\n" +
            "uqhwacyl\n" +
            "cuaywq\n" +
            "mzecqyuwa\n" +
            "uahqcwy\n" +
            "\n" +
            "u\n" +
            "u\n" +
            "xvruq\n" +
            "u\n" +
            "u\n" +
            "\n" +
            "zytrqed\n" +
            "fnqzeyd\n" +
            "\n" +
            "umrefq\n" +
            "jwficzvnoply\n" +
            "krufsa\n" +
            "\n" +
            "y\n" +
            "y\n" +
            "dn\n" +
            "\n" +
            "condu\n" +
            "cufnwgshxz\n" +
            "cnu\n" +
            "icnju\n" +
            "icnu\n" +
            "\n" +
            "kgbns\n" +
            "klnbg\n" +
            "nmebg\n" +
            "gbdnyufaj\n" +
            "\n" +
            "vehocbtkpfm\n" +
            "qztsmfb\n" +
            "dgmflbit\n" +
            "bqzmfgt\n" +
            "lfmzbt\n" +
            "\n" +
            "krgoxqldeatmibvc\n" +
            "tdxkvbegmlaoc\n" +
            "ctamlkvdegbrxo\n" +
            "vbdktgmoalzxecp\n" +
            "\n" +
            "z\n" +
            "z\n" +
            "z\n" +
            "z\n" +
            "\n" +
            "w\n" +
            "v\n" +
            "v\n" +
            "v\n" +
            "v\n" +
            "\n" +
            "obplutfcjih\n" +
            "iofcuhtj\n" +
            "\n" +
            "xbzosrulkjy\n" +
            "zoxjuskrly\n" +
            "ujyslrokxnz\n" +
            "yzsoklxujr\n" +
            "\n" +
            "wkctfpmehxs\n" +
            "wvisua\n" +
            "sjlznw\n" +
            "\n" +
            "pwvqg\n" +
            "btxvpwq\n" +
            "qvpdw\n" +
            "wspqv\n" +
            "povqw\n" +
            "\n" +
            "ypkudorxbfvgwzqatci\n" +
            "cvkuasjywbxo\n" +
            "hcbokwxuvyan\n" +
            "keabmoyxlvucw\n" +
            "\n" +
            "aprsibm\n" +
            "dui\n" +
            "iydcu\n" +
            "\n" +
            "lhbmdio\n" +
            "ihldbom\n" +
            "hmliobdn\n" +
            "\n" +
            "bulyqrtixdpnz\n" +
            "naitduzhqclprb\n" +
            "\n" +
            "wu\n" +
            "u\n" +
            "uql\n" +
            "uy\n" +
            "u\n" +
            "\n" +
            "qmnr\n" +
            "nr\n" +
            "rn\n" +
            "nr\n" +
            "\n" +
            "t\n" +
            "tf\n" +
            "t\n" +
            "t\n" +
            "\n" +
            "r\n" +
            "g\n" +
            "g\n" +
            "\n" +
            "zu\n" +
            "kz\n" +
            "bmnzyp\n" +
            "caudz\n" +
            "\n" +
            "etqca\n" +
            "eqta\n" +
            "qeat\n" +
            "eqat\n" +
            "qfkladet\n" +
            "\n" +
            "pwjvzfaeiqrhkg\n" +
            "azjcnghdwympkr\n" +
            "\n" +
            "uiomdytbqsck\n" +
            "miodubqcykst\n" +
            "\n" +
            "gow\n" +
            "wgo\n" +
            "ogw\n" +
            "wgo\n" +
            "ongw\n" +
            "\n" +
            "f\n" +
            "f\n" +
            "\n" +
            "tu\n" +
            "tu\n" +
            "ut\n" +
            "tu\n" +
            "\n" +
            "orjcylmtqfws\n" +
            "jmywqlhofaugcsr\n" +
            "ifcrmuwqoly\n" +
            "vzlpknwyfqecxrodmb\n" +
            "\n" +
            "yil\n" +
            "lzy\n" +
            "ely\n" +
            "\n" +
            "mu\n" +
            "smcluy\n" +
            "ftgzj\n" +
            "dh\n" +
            "\n" +
            "dnw\n" +
            "dwn\n" +
            "wndo\n" +
            "ndw\n" +
            "dnw\n" +
            "\n" +
            "wxbvfljri\n" +
            "wfrbixvlj\n" +
            "fmibpywjxlr\n" +
            "ijxlegfrwb\n" +
            "\n" +
            "pnvlk\n" +
            "yvnk\n" +
            "\n" +
            "finwu\n" +
            "nuw\n" +
            "yncwu\n" +
            "maiugwn\n" +
            "xwnfmu\n" +
            "\n" +
            "qyzkvwlrj\n" +
            "yqjzlv\n" +
            "vqtyzl\n" +
            "cdhyfvzlsagq\n" +
            "vyqrlzw\n" +
            "\n" +
            "aervczodlixbmkuqwst\n" +
            "kbtsnjhfyxzw\n" +
            "\n" +
            "rfbykpxamcnqdg\n" +
            "qkrnapgcmxdbfy\n" +
            "cmbgdrnkqyjaxf\n" +
            "gdkmcbayxqfnr\n" +
            "\n" +
            "runivm\n" +
            "qxytswonubpahfe\n" +
            "ldvjun\n" +
            "vczngu\n" +
            "\n" +
            "j\n" +
            "z\n" +
            "\n" +
            "zrbvdpgykiqea\n" +
            "kdvwzaiyregqp\n" +
            "dxpkaievzrgyq\n" +
            "akgcqvidpylzjsre\n" +
            "\n" +
            "n\n" +
            "x\n" +
            "n\n" +
            "s\n" +
            "\n" +
            "ij\n" +
            "qyij\n" +
            "\n" +
            "dlyctwiqkrnhomajbxzgpsuefv\n" +
            "naqrodiyzejvcmkbhspxtgfwlu\n" +
            "hgotncquakzyflmxwevprsdjbi\n" +
            "\n" +
            "wxhriozjbnsdqpeftykgvm\n" +
            "noqdjrsixpfegwykvtblmh\n" +
            "wpsbvrhjdtkyonigqmexf\n" +
            "qwnexrjdtobvsahmpfgyik\n" +
            "hoerbsqpyivmtdxgnfjkw\n" +
            "\n" +
            "kaqtcsyzvoilgfu\n" +
            "ctuyfaslgwoqndez\n" +
            "\n" +
            "vlxujg\n" +
            "vdzqebysi\n" +
            "vxojgw\n" +
            "kv\n" +
            "\n" +
            "kqmrbtedvplcons\n" +
            "wdqmcovykrlg\n" +
            "kdujrcqmlhofa\n" +
            "\n" +
            "hujqdpyzg\n" +
            "hjqguda\n" +
            "gqwizdhjum\n" +
            "\n" +
            "nsrzk\n" +
            "nk\n" +
            "nk\n" +
            "nk\n" +
            "kn\n" +
            "\n" +
            "mvozjeadkyiuqwtgrlp\n" +
            "mqezpkyvlhajntbugw\n" +
            "alwtuyzvmqjepkng\n" +
            "euwmltqzygvkjpa\n" +
            "\n" +
            "vpqfsjdylgecuizkxaro\n" +
            "mrlfuyvgadocieskqzxpj\n" +
            "pltswakzqcebgnuyfxjhrvdio\n" +
            "fejdlprausgoxqivyckz\n" +
            "iaqpkeozyrcugfdjxslv\n" +
            "\n" +
            "feshunjdyrkpz\n" +
            "syofqrnzpelwkvahgx\n" +
            "fhszymeknprdtj\n" +
            "\n" +
            "pxjh\n" +
            "jyi\n" +
            "gdj\n" +
            "ijyt\n" +
            "\n" +
            "hcxwbldj\n" +
            "kptnqau\n" +
            "\n" +
            "jhmrnue\n" +
            "mjhen\n" +
            "iandxscqemj\n" +
            "jmnrve\n" +
            "\n" +
            "cfbqlyvjmrdn\n" +
            "mvcqodbrjyln\n" +
            "qbcuyrdjvxlmn\n" +
            "lghsydmrqvcktnjb\n" +
            "\n" +
            "dcnisejazf\n" +
            "nsvfiaye\n" +
            "uepirnbsaft\n" +
            "xsaizefn\n" +
            "\n" +
            "jfidqhkgvmcanou\n" +
            "favcmjnqgohkdui\n" +
            "gdqoknhmjaucifv\n" +
            "ogacvinhjqdumkf\n" +
            "ivfumakhondqcgj\n" +
            "\n" +
            "nk\n" +
            "tu\n" +
            "\n" +
            "ltwubkpry\n" +
            "wkyrulst\n" +
            "rkutwyb\n" +
            "twxeuorkyjaq\n" +
            "khygfrtuwv\n" +
            "\n" +
            "riklmxy\n" +
            "toxzyujcwg\n" +
            "kydxabhl\n" +
            "qhpdyex\n" +
            "\n" +
            "dxrsczbgi\n" +
            "ibrxpzdg\n" +
            "rixgzbpd\n" +
            "rzjxigblwmd\n" +
            "xbdgcriz\n" +
            "\n" +
            "bdkosnwg\n" +
            "hptwavs\n" +
            "wosg\n" +
            "\n" +
            "fytbweiqrd\n" +
            "iem\n" +
            "ei\n" +
            "ei\n" +
            "hiem\n" +
            "\n" +
            "cgldnk\n" +
            "dnicgvk\n" +
            "kncgdr\n" +
            "\n" +
            "zbtmgxspadkylnerjfivwc\n" +
            "koghdbqplitywmjzcfnxsurae\n" +
            "\n" +
            "ziesxa\n" +
            "xkai\n" +
            "aybxi\n" +
            "xtai\n" +
            "\n" +
            "uvlwbn\n" +
            "arbuwvnl\n" +
            "blnwvu\n" +
            "lvmbnuw\n" +
            "uflcwvbn\n" +
            "\n" +
            "wj\n" +
            "laj\n" +
            "jrks\n" +
            "jz\n" +
            "\n" +
            "paoxnbwidzqecj\n" +
            "cbjqzndxioaew\n" +
            "wjcgzblidnexotqa\n" +
            "\n" +
            "undrbvjazkxfwm\n" +
            "rbjgmavwkfnd\n" +
            "bvdkarohjmwfinq\n" +
            "\n" +
            "ztjgylusnhkwmdpcfaer\n" +
            "ejzhlxabwpcgrqymfks\n" +
            "\n" +
            "rboazst\n" +
            "fev\n" +
            "l\n" +
            "y\n" +
            "\n" +
            "stzbhglu\n" +
            "tzwbgklm\n" +
            "lgbtkzq\n" +
            "\n" +
            "swlhoaey\n" +
            "ijecmrtv\n" +
            "\n" +
            "fpgusrznxmjiwky\n" +
            "wmiupyfzstjgnrx\n" +
            "wjypusngirfzxm\n" +
            "pjfgiumrnwysxz\n" +
            "yijmrfszawpguxn\n" +
            "\n" +
            "jzuondf\n" +
            "fpwkcg\n" +
            "\n" +
            "gj\n" +
            "gj\n" +
            "gj\n" +
            "jg\n" +
            "\n" +
            "apxbyduwrzvhiqnotecmk\n" +
            "zbxnvdwecahyoutkrmqpi\n" +
            "dwmeafckuvbyphxtnqzoir\n" +
            "ztswbvqlehonyiagukpcmrxd\n" +
            "\n" +
            "epyahzmivfoxdcrubskj\n" +
            "wezaqkisrnodxjmbcuh\n" +
            "\n" +
            "mivkr\n" +
            "pvmugk\n" +
            "jvpkcm\n" +
            "\n" +
            "fsdjmwkhqelz\n" +
            "legdqhsfjwmz\n" +
            "hdqzekjslmfw\n" +
            "zqfhmlyejwds\n" +
            "zshemkljdwfq\n" +
            "\n" +
            "eibptzmws\n" +
            "pdiwezovabmt\n" +
            "etwyzbpmri\n" +
            "mnpwbteuzi\n" +
            "nzfmitpwbe\n" +
            "\n" +
            "kmo\n" +
            "kom\n" +
            "okm\n" +
            "kom\n" +
            "\n" +
            "ujmz\n" +
            "vjaz\n" +
            "jz\n" +
            "\n" +
            "aqtgbhmknexouplv\n" +
            "oplqjutbyenmvxkagh\n" +
            "fgnbwklchvdamotpuxeq\n" +
            "euapytnmhqovgkbxl\n" +
            "\n" +
            "shbmrnoqdacv\n" +
            "lbzmikpeojqs\n" +
            "\n" +
            "dtmufyeshikonvcrbzap\n" +
            "krcphwzfbo\n" +
            "qfhzrgxpbkjoc\n" +
            "\n" +
            "idgusvbeqrokjzmhyapcwnlxtf\n" +
            "godcwmnrbsxktlpehqijyavzuf\n" +
            "\n" +
            "zoikpdh\n" +
            "kdzxpo\n" +
            "yodezkfrp\n" +
            "zslgmopkbtd\n" +
            "pdozfk\n" +
            "\n" +
            "hnpdkeoqzmljbu\n" +
            "lhrdwsyxcukogivnabt\n" +
            "\n" +
            "qailhuryopcsewdnkbxfmjz\n" +
            "nmljvdxibtqapkucsoyrzfewh\n" +
            "cgapwlsonbmxekuqjrzyhdif\n" +
            "\n" +
            "lseiogtaykwpjvxzmbqhfucr\n" +
            "mpxvfuljayzkshrtqgwbeico\n" +
            "\n" +
            "acsfyhpkizetowrblm\n" +
            "ehytpcsriaflkbzmwo\n" +
            "\n" +
            "fkmvgxnad\n" +
            "jyiqwos\n" +
            "owbur\n" +
            "\n" +
            "rf\n" +
            "f\n" +
            "rf\n" +
            "xf\n" +
            "\n" +
            "htqudbfwcrzkyisganv\n" +
            "qdisahkzucbfrytwvgn\n" +
            "hkynuwcbgqtrifavsdz\n" +
            "tabkzuqgrfhwcvsyindm\n" +
            "\n" +
            "owtzqplauxgfyecsmnjr\n" +
            "eulgncpmjszxtqyfowra\n" +
            "pxjailfskqywrnzmucohegbt\n" +
            "fzpreujmqcwtgsloxnyva\n" +
            "sarecmqfuvonxtyzpljgw\n" +
            "\n" +
            "ixuylwrvmjqopzhacnsgbfkte\n" +
            "yrjefzhgtmpqncxvisbklwaou\n" +
            "zaornisymxegujlbfwkchtqpv\n" +
            "rsoklpwytmencjhbgxuqafvizd\n" +
            "iambcjokxzhtgvqrwnflyspeu\n" +
            "\n" +
            "mqinhscjobfuregvpkdw\n" +
            "roflkwnigjdmcbhsvpuqe\n" +
            "ojchiyqpswkbunemfrvdg\n" +
            "\n" +
            "vdqxkcy\n" +
            "lsrpwizheuan\n" +
            "\n" +
            "iceuf\n" +
            "vifeup\n" +
            "wifsuec\n" +
            "uebizxqfmg\n" +
            "ieufwr\n" +
            "\n" +
            "uxlwm\n" +
            "xwuml\n" +
            "rulsqpedzmw\n" +
            "mulwt\n" +
            "mlwtyu\n" +
            "\n" +
            "cgukthfdrleyqnoz\n" +
            "qytznodclkrgehfu\n" +
            "zgktqnlreuodchyjf\n" +
            "zeocuryhlqnktgfd\n" +
            "\n" +
            "jviwfprdxunlqsazhygm\n" +
            "obcikrjatmepv\n" +
            "\n" +
            "djrfnkuelt\n" +
            "bxwrypsaqnizgtohcl\n" +
            "ftnemvlur\n" +
            "\n" +
            "c\n" +
            "l\n" +
            "c\n" +
            "\n" +
            "wkhxcmtqnf\n" +
            "tjfyhxip\n" +
            "\n" +
            "plytx\n" +
            "xlpt\n" +
            "ptlxbza\n" +
            "xiptl\n" +
            "lpxtc\n" +
            "\n" +
            "ut\n" +
            "ut\n" +
            "tun\n" +
            "tu\n" +
            "\n" +
            "gojwnh\n" +
            "tapjweo\n" +
            "jkwsoz\n" +
            "nptwjo\n" +
            "owyjfib\n" +
            "\n" +
            "vazl\n" +
            "vzslau\n" +
            "lzyvua\n" +
            "lzvram\n" +
            "\n" +
            "n\n" +
            "n\n" +
            "u\n" +
            "n\n" +
            "\n" +
            "nti\n" +
            "int\n" +
            "nti\n" +
            "\n" +
            "eqy\n" +
            "qncev\n" +
            "xwfe\n" +
            "eyon\n" +
            "\n" +
            "fyvultxjdgw\n" +
            "ecljt\n" +
            "ainqkpsjlobtm\n" +
            "\n" +
            "pgntz\n" +
            "byjpvkxmn\n" +
            "idu\n" +
            "kglpzxv\n" +
            "jhzst\n" +
            "\n" +
            "hn\n" +
            "hzn\n" +
            "nh\n" +
            "\n" +
            "lmvzfqx\n" +
            "xzqfulvm\n" +
            "fmzxqlv\n" +
            "vlqfxzm\n" +
            "\n" +
            "gsiuwrczj\n" +
            "uwcirzsj\n" +
            "urwsjzic\n" +
            "cijusrwz\n" +
            "\n" +
            "jmzveqfclwpd\n" +
            "zlqmdjwcepgvf\n" +
            "pufyqwdtbnmzljcv\n" +
            "\n" +
            "ljzicfgkqusv\n" +
            "cqvfjzsgikbrlmu\n" +
            "qijfsklugvhzc\n" +
            "\n" +
            "phwqbjmoat\n" +
            "jpaoiktbqwm\n" +
            "gqmwpoatjb\n" +
            "tpvfmjqzawosr\n" +
            "pmolqnwjtea\n" +
            "\n" +
            "mndxkegtvbrq\n" +
            "gxbrjqkvieyd\n" +
            "qxbvkedrg\n" +
            "\n" +
            "ejk\n" +
            "j\n" +
            "uhjd\n" +
            "\n" +
            "gnpuomqsczeh\n" +
            "nuzijsechdmo\n" +
            "ykwohmcztexrbnu\n" +
            "suzcojemlaqvnfh\n" +
            "\n" +
            "cxns\n" +
            "c\n" +
            "cbv\n" +
            "c\n" +
            "\n" +
            "sglxydakoqjmfpwncu\n" +
            "mazrvtencdub\n" +
            "\n" +
            "uz\n" +
            "ckug\n" +
            "ui\n" +
            "u\n" +
            "u\n" +
            "\n" +
            "ncgouzbesahkim\n" +
            "bnkmjo\n" +
            "bmoknw\n" +
            "obmpntfk\n" +
            "mnkqbo\n" +
            "\n" +
            "jnqgixtohes\n" +
            "stiexgpjohnq\n" +
            "exioqnhsgjt\n" +
            "sxtngoejhiq\n" +
            "\n" +
            "asvtq\n" +
            "k\n" +
            "lftxqrb\n" +
            "qnb\n" +
            "pjde\n" +
            "\n" +
            "tdrozlxfshiw\n" +
            "cxplyaeqrnjmubgtv\n" +
            "\n" +
            "navw\n" +
            "ouw\n" +
            "\n" +
            "yonraj\n" +
            "eryjnao\n" +
            "ayrojkn\n" +
            "\n" +
            "mxysoptf\n" +
            "tbsmypfxo\n" +
            "yofsmptx\n" +
            "pxofmstyq\n" +
            "fstpmyxo\n" +
            "\n" +
            "pzyn\n" +
            "nzyp\n" +
            "zpny\n" +
            "ynzp\n" +
            "pzyn\n" +
            "\n" +
            "zyhcfse\n" +
            "hyscze\n" +
            "zycseh\n" +
            "zheycs\n" +
            "\n" +
            "gcouisqaxlrvejydphmbt\n" +
            "jmitxhzpvrkedlycgabuosq\n" +
            "\n" +
            "ivrntbe\n" +
            "tenivb\n" +
            "vtnbie\n" +
            "\n" +
            "yjizefmgdkaxv\n" +
            "ivydxfaemgjhkz\n" +
            "ovcdmaebxwyukzjgi\n" +
            "evhimadzjgykxl\n" +
            "\n" +
            "nvlsp\n" +
            "snlp\n" +
            "plsn\n" +
            "\n" +
            "fbpzqdiasx\n" +
            "sfpzajbiqxd\n" +
            "fsbiqadpxz\n" +
            "\n" +
            "n\n" +
            "fnl\n" +
            "inw\n" +
            "n\n" +
            "\n" +
            "hpydugkiazcwojsv\n" +
            "epchvgtbuirn\n" +
            "\n" +
            "bkuga\n" +
            "maofiw\n" +
            "vka\n" +
            "\n" +
            "pfjwql\n" +
            "jwfmolu\n" +
            "tdwp\n" +
            "pfomwvb\n" +
            "kceywi\n" +
            "\n" +
            "hsbtrodwjuqzga\n" +
            "gbdsqtvzorauw\n" +
            "qrszogbtadw\n" +
            "gpblwatnxrsdfzqo\n" +
            "\n" +
            "pvjhdz\n" +
            "dvopjh\n" +
            "jhuvly\n" +
            "\n" +
            "drpc\n" +
            "rlpz\n" +
            "\n" +
            "bwhkzcqxu\n" +
            "pzfomwtqs\n" +
            "zdqnxwg\n" +
            "\n" +
            "lgeqvjzaxiw\n" +
            "thvaywui\n" +
            "aivwfhmy\n" +
            "\n" +
            "shmfjyrgdbvip\n" +
            "tojvnqpgbxksfrad\n" +
            "bmgrshcdvjfp\n" +
            "zcerjsdpfgbhv\n" +
            "\n" +
            "yfgu\n" +
            "gidfy\n" +
            "mfy\n" +
            "\n" +
            "xafkiu\n" +
            "qxaibuk\n" +
            "\n" +
            "rwnzdfj\n" +
            "njtwdf\n" +
            "jufnbwid\n" +
            "njwdf\n" +
            "\n" +
            "fcti\n" +
            "xil\n" +
            "miud\n" +
            "\n" +
            "ufsljiomb\n" +
            "oifljsbmu\n" +
            "osjbifqulm\n" +
            "ijtpsmubfol\n" +
            "jfcuobilmws\n" +
            "\n" +
            "urimpzvkwh\n" +
            "rkwmcpizvyuh\n" +
            "\n" +
            "qsmrxznjhyakovdlbg\n" +
            "gkbvzoyhjasxrdmlqn\n" +
            "glnbcdjyzwaoqxhrmsvk\n" +
            "\n" +
            "yqxhzp\n" +
            "zxqh\n" +
            "zhqxebn\n" +
            "xqihz\n" +
            "\n" +
            "nsmkjgrqyez\n" +
            "gwkzmcbduov\n" +
            "camkghz\n" +
            "\n" +
            "ndjyewmtrflbxkvi\n" +
            "fxidynwjtkbmrevl\n" +
            "\n" +
            "xi\n" +
            "o\n" +
            "j\n" +
            "b\n" +
            "bm\n" +
            "\n" +
            "gbukjdtx\n" +
            "skzjxgbmt\n" +
            "txqejbgfhprk\n" +
            "lmtjxykzanbg\n" +
            "\n" +
            "mtqlhzwa\n" +
            "zawqhlt\n" +
            "\n" +
            "amscyopkbnewlud\n" +
            "plndsweamtobyckquh\n" +
            "aypntosdcebkumlw\n" +
            "apmeyduoklnbjcsw\n" +
            "\n" +
            "gt\n" +
            "o\n" +
            "\n" +
            "pwlgxaurefnvhsz\n" +
            "lzevfhbpanux\n" +
            "\n" +
            "dfuijyeasc\n" +
            "iecshjfdy\n" +
            "\n" +
            "axvduikeslfy\n" +
            "akfolydevis\n" +
            "lesiyvdafk\n" +
            "\n" +
            "ghbikrtxv\n" +
            "trkebigx\n" +
            "\n" +
            "zbsluxv\n" +
            "uzxlbvs\n" +
            "slzxvub\n" +
            "lxvbszu\n" +
            "sbzulxv";
}
